### ISSUE TITLE
Move to flathub organization

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/net.lutris.Lutris#12]
https://github.com/flathub/net.lutris.Lutris

**Comment by Saladin1812** [comment]
Will the flatpak contain wine and vulkan ? Because i dont think flatpaks can actually use system dependencies.

**Comment by gasinvein** [comment]
Vulkan is included in the runtime.
Wine could be added as an extension, but do we really need it? Lutris downloads it's own wine builds anyway.
>i dont think flatpaks can actually use system dependencies

Yes, flatpaks are self-contained.

**Comment by Saladin1812** [comment]
Actually i think we do need because on lutris download page it says that even if lutris downloads wine builds there are some deps required which lutris runtime is unable to provide so we do need wine-staging

**Comment by gasinvein** [comment]
Do you mean we need to include wine dependencies to run Lutris-provided wine builds, or we need wine itself to be bundled?
Wine in this flatpak seems to be working already https://github.com/flathub/flathub/pull/919#issuecomment-476361635

**Comment by Saladin1812** [comment]
![Screenshot_20190330-164101_Samsung Internet](https://user-images.githubusercontent.com/40650341/55275333-b3a19400-530a-11e9-91e6-681393ec3e2a.jpg)
This is what lutris says it says that its required to have recent version of wine

**Comment by RobLoach** [comment]
When it's not installed on the system you get this dialog box:

![Screenshot at 2019-03-30 07-24-46](https://user-images.githubusercontent.com/25086/55275468-ede44480-52bc-11e9-8909-adfabceaa659.png)

I have often ignored this message, and had wine games work properly. May need clarification from @strycore on whether this is still the case.

**Comment by gasinvein** [comment]
@jatin-cbs Opened #15, please move the wine discussion there.
