### ISSUE TITLE
Diablo III / Starcraft II via Battle.Net Close on Startup

### ISSUE THREAD

**Issue by rcannizzaro** [RobLoach/net.lutris.Lutris#18]
Just testing out the newest builds. I can't get Diablo III or Starcraft II to run via the Battle.Net app (which installs and runs fine). Both games close on startup - Diablo III gives me a mouse cursor and then closes and Starcraft II shows the loading image and then closes with an unhandled exception. I can run Hearthstone with no issues so it's not every Battle.Net game.

I'm thinking it may be dependency related but I'm not sure. I have run Lutris in debug mode but didn't see any useful output.

Could anyone point me in the right direction for getting logs for this so that I can report back on this? I'm also keen on helping out (although I'm new to the Flatpak world).

Help appreciated :)

**Comment by lionirdeadman** [comment]
I believe this is due to missing wine dependencies discussed in #15

**Comment by gasinvein** [comment]
I was able to run Starcraft II and Diablo III by running the binaries (`Support64/SC2Switcher_x64.exe` and `x64/Diablo III64.exe`) directly with `-launch` argument. Does this work for you?
NB: 32-bit wine is still broken https://github.com/flathub/flathub/pull/926#issuecomment-478231140

**Comment by rcannizzaro** [comment]
@gasinvein thanks, I've tried but there was no difference. I'll get some game logs later. I'm running Fedora Silverblue 30 although given this is all sandboxed I doubt that makes a difference.

Diablo 3 was an existing set of files, SC2 a new download. I've verified the files of both. I tried using the battle.net installer and the Diablo 3 one.

I'm running a RX480 (Mesa) on a Ryzen CPU.

**Comment by gasinvein** [comment]
Does running with `--allow=devel` (`flatpak run --allow=devel net.lutris.Lutris`) help? For me it does, just didn't realize it before.

**Comment by rcannizzaro** [comment]
@gasinvein That's it! It's working now :D 
Two questions: one- how did you figure that out? And two, how do we add those permissions?

**Comment by gasinvein** [comment]
>how did you figure that out?

Accidentally. I've been running Lutris sandbox with `--allow=devel --command=bash` most of the time to debug things, so StartCraft II worked for me from the start. And once I've ran it via desktop launcher, it stopped working.
It must be for Blizzard games wine is using some syscalls which are filtered by default, but allowd for development.

>how do we add those permissions?

Add it as is to `finish-args`.
