### ISSUE TITLE
installation not working after the commit 757d68b mesa-demos

### ISSUE THREAD

**Issue by Saladin1812** [RobLoach/net.lutris.Lutris#19]
After the last mesa-demos commit installation gives out this error on the command 
`flatpak-builder --user --repo=lutris --force-clean build-dir net.lutris.Lutris.yml`

https://pastebin.com/h0xzrVmN

Error: module mesa-demos: Child process exited with code 1

**Comment by Saladin1812** [comment]
It says glew >= 1.5.4 is needed

**Comment by gasinvein** [comment]
I guess you forget to pull the submodules.
https://github.com/RobLoach/net.lutris.Lutris/blob/757d68b2a82884abb5e4039c05b5df3c2e3c1014/net.lutris.Lutris.yml#L224-L226
Run `git submodule update --init` before building.

**Comment by Saladin1812** [comment]
Not working please can you update the readme ?

**Comment by gasinvein** [comment]
You can just install automated build provided by Flathub's buildbot https://github.com/flathub/flathub/pull/926#issuecomment-478499020
