### ISSUE TITLE
Flatpaked Steam Not Detected

### ISSUE THREAD

**Issue by Saroufim** [RobLoach/net.lutris.Lutris#33]
With the release of 0.5.2, Lutris should have been able to detect Steam distributed via flatpak yet it doesn't. Lutris installed via RPM detects the flatpaked Steam just fine.

**Comment by RobLoach** [comment]
You installed Lutris through Flatpak? 0.5.2? Latest master?

**Comment by Saroufim** [comment]
Lutris through Flatpak based on this project as compiled by the Flathub. It should contain the patch that detects Flatpaked Steam. In any case, I found out that it's not just Steam. It doesn't detect any flatpaked game at all. Supertuxkart, intalled from Flathub, is also not detected.

**Comment by gasinvein** [comment]
So you meant Lutris doesn't detect Steam itself, not games from steam library?
If it doesn't detect native games - it is kinda expected, while we can make Lutris find them, it won't be able to run them anyway.

**Comment by Saroufim** [comment]
It doesn't detect steam itself, native games, or proton-enabled games; basically it detects nothing that comes in a flatpak.

**Comment by gasinvein** [comment]
Sorry, I don't get it. Can you please explain like this?
1. What you do
2. What you expect to happen
3. What it actually happening

**Comment by Saroufim** [comment]
1 - flatpak run net.lutris.Lutris
2 - Flatpaked Lutris to show the same identical library that non-flatpaked lutris shows including Steam itself (which is flatpaked on my system), Steam's games including native and proton-based ones, and native games (flatpaked on my system)
3 - Flatpaked Lutris only shows wine-based games in my library and does not detect Steam nor its games and neither does it detect non-steam native games.

**Comment by gasinvein** [comment]
Was it different with previous Lutris flatpak builds?
>Flatpaked Lutris to show the same identical library that non-flatpaked lutris

No, this is not how it works. Flatpak'ed apps are self-contained, so is their data, which is independent from the host's data. You have to re-import games from Steam library. Flatpak'ed Lutris should be able to scan flatpak'ed Steam library - this is the thing that was fixed in v0.5.2.

>Flatpaked Lutris only shows wine-based games

I guess it's because flatpak'ed Lutris has direct access to `~/Games` directory. This may it change in future.

**Comment by Saroufim** [comment]
You're right. I assumed it would scan the directory automatically but I had to import the games manually. All the games were listed but not all of them were automatically imported. Path of Exile, Elder Scrolls Online, and Elder Scrolls Legends were not for instance.

**Comment by gasinvein** [comment]
>not all of them were automatically imported

If you have multiple steam libraries, e.g. on separate partitions, you should give flatpak'ed Lutris access to them, like so: `flatpak override net.lutris.Lutris --filesystem=/path/to/your/games`.

**Comment by Saroufim** [comment]
They're all installed under ~/.var/app/com.valvesoftware.Steam

**Comment by gasinvein** [comment]
Is this resolved?

**Comment by Saroufim** [comment]
Yes this has been successfully resolved.
