### ISSUE TITLE
Missing Vulkan Libraries

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/net.lutris.Lutris#43]
I've heard we may need a symlink for it to find it correctly?

![Screenshot at 2019-05-08 16-54-36](https://user-images.githubusercontent.com/25086/57407774-fb40f880-71b1-11e9-8db6-21d8205b8743.png)

**Comment by gasinvein** [comment]
Since 32-bit vulkan actually do work, this can be safely ignored, so "after release".

How does Lutris check it?

**Comment by gasinvein** [comment]
Do you test with latest build? This should be fixed after #39.

**Comment by RobLoach** [comment]
Nice! I'll try out the latest build in the next few hours. :+1:

**Comment by RobLoach** [comment]
The check is over at https://github.com/lutris/lutris/blob/e189003754519cd1945be64b4154f7319701eba1/lutris/startup.py#L103-L109

**Comment by Saladin1812** [comment]
I tested it 2 days before I was able to install and run battle net with DXVK. The Dialog box maybe is just lutris checking in different path it can be ignored or can be removed here.

**Comment by gasinvein** [comment]
I believe this is fixed since #39. Reopen if not.
