### ISSUE TITLE
BMW m3 challenge error to install

### ISSUE THREAD

**Issue by fastoslinux** [RobLoach/net.lutris.Lutris#46]
BMW M3 challenge error to install

https://paste.fedoraproject.org/paste/XDQBdzjScfMIUMZzawgLTQ

**Comment by gasinvein** [comment]
You log says
```
2019-05-12 21:02:56,318: Downloading file 1 of 1
2019-05-12 21:02:58,035: Downloaded file is empty
```
and the url in [the installer script](https://lutris.net/games/install/6042/view) gives HTTP error 404, so this issue is clearly neither with Lutris nor with this flatpak.
