### ISSUE TITLE
Wine Game Saves Are Not Persistent

### ISSUE THREAD

**Issue by Saroufim** [RobLoach/net.lutris.Lutris#49]
Many wine games place their saves in ~/Documents which Lutris does not have default access to. Using the "Sandbox" feature to create a new user directory inside the wineprefix is somehow buggy as games do not detect their own saves. Two possible solutions would be:

- Grant access to ~/Documents
- Take the issue upstream to Lutris and figure out exactly what is the issue with sandboxing.

**Comment by gasinvein** [comment]
What's that sandbox feature?

**Comment by Saroufim** [comment]
It's a feature in Lutris that confines the wine app inside the a folder (usually the wine prefix it runs from but the user can change that) and thus a new Home (with documents, music, downloads, and the rest of the subfolders) is created for that specific wine app isolating it from ~/home.

**Comment by gasinvein** [comment]
Is there a default for this folder location?

**Comment by Saroufim** [comment]
Yes. It's usually under drive_c/users/ inside the prefix the game runs in.

**Comment by gasinvein** [comment]
So is it equivalent to unticking "Link to" options in wine configuration?

**Comment by Saroufim** [comment]
I would assume so, yes. It does not seem to provide any additional functionality beyond that.

**Comment by RobLoach** [comment]
`xdg-documents` is now in the filesystem perms. Mind testing again? Feel free to re-open if ~/Documents access isn't there.

**Comment by lionirdeadman** [comment]
@RobLoach I think granting access to individual folders in the user's HOME is not viable, it's better to remove the symlinks that WINE creates.
