### ISSUE TITLE
x11-xserver-utils

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/net.lutris.Lutris#6]
or the package providing 'xrandr', if you are running Xorg, if you are not, you will depend on the GnomeDesktop bindings to fetch screen resolutions on Wayland, the GnomeDesktop library is not directly related to the Gnome desktop and is only used as a xrandr replacement

**Comment by gasinvein** [comment]
Already included in 8bec4ddff700ae634011e3c37ab3f548d87317c8
